name: geo_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - _openmp_mutex=4.5
  - affine=2.4.0
  - asttokens=3.0.0
  - attrs=25.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.0
  - aws-c-common=0.12.3
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.10.1
  - aws-c-io=0.19.0
  - aws-c-mqtt=0.13.0
  - aws-c-s3=0.7.17
  - aws-c-sdkutils=0.2.3
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.5
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - blosc=1.21.6
  - boost-cpp=1.78.0
  - branca=0.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cairo=1.18.4
  - capnproto=1.0.2
  - certifi=2025.4.26
  - cffi=1.17.1
  - cfitsio=4.6.2
  - charset-normalizer=3.4.2
  - click=8.2.1
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.2
  - curl=8.13.0
  - cycler=0.12.1
  - debugpy=1.8.14
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.0
  - fmt=11.1.4
  - folium=0.19.6
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - freetype
  - freexl
  - gdal=3.10.3
  - geopandas=1.0.1
  - geos=3.13.1
  - geotiff=1.7.4
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - h2=4.2.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - intel-openmp=2024.2.1
  - ipykernel=6.29.5
  - ipython=8.36.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kealib=1.6.2
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  